export const AUTHENTICATE = 'AUTHENTICATE';
export const DEAUTHENTICATE = 'DEAUTHENTICATE';
export const STORE_USERS_LIST  = 'STORE_USERS_LIST';
export const STORE_POSTS_LIST  = 'STORE_POSTS_LIST';
export const STORE_COMMENTS_LIST  = 'STORE_COMMENTS_LIST';