export const FETCH_POST_COMMENTS ='FETCH_POST_COMMENTS';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const UPDATE_COMMENT  = 'UPDATE_COMMENT';
export const DELETE_COMMENT  = 'DELETE_COMMENT';